[package]
name = "mirror-shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "mirror"

[dependencies]
anyhow = "1.0.82"
log = "0.4.20"
common = { path = "../common" }

[target.'cfg(target_os = "android")'.dependencies]
bytes = "1.5"
jni = "0.21.1"
num_cpus = "1.16.0"
transport = { path = "../transport" }

[target.'cfg(not(target_os = "android"))'.dependencies]
mirror = { path = "../mirror" }
