[package]
name = "mirror-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "mirror"

[dependencies]
anyhow = "1.0.82"
bytes = "1.5"
log = "0.4.20"
utils = { path = "../utils" }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
num_cpus = "1.16.0"
parking_lot = "0.12"
transport = { path = "../transport" }

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
mirror = { path = "../mirror" }
