[package]
name = "mirror"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bytes = "1.5"
crossbeam = "0.8"
utils = { path = "../common/utils" }
frame = { path = "../common/frame" }
transport = { path = "../transport" }
log = "0.4.20"

[target.'cfg(target_os = "windows")'.dependencies]
capture = { path = "../capture" }
codec = { path = "../codec" }
cpal = "0.15.3"
windows = "0.58.0"
