[package]
name = "mirror"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bytes = "1.5"
crossbeam = "0.8"
log = "0.4.20"
utils = { path = "../common/utils" }
frame = { path = "../common/frame" }
transport = { path = "../transport" }

[target.'cfg(not(target_os = "android"))'.dependencies]
capture = { path = "../capture" }
codec = { path = "../codec" }
cpal = "0.15.3"
wgpu = "22.1.0"
pollster = "0.3.0"
bytemuck = { version = "1.17.1",  features = ["derive"] }
