[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "22.1.0"
pollster = "0.3.0"
thiserror = "1.0.63"
smallvec = "1.13.2"
bytemuck = { version = "1.17.1",  features = ["derive"] }
utils = { path = "../common/utils" }

[target.'cfg(target_os = "windows")'.dependencies]
d3d12 = "22.0.0"
