[profile.release]
debug-assertions = false
overflow-checks = false
strip = "debuginfo"
panic = "abort"
debug = false
lto = true

[workspace]
resolver = "2"
members = [
    "codec", 
    "transport", 
    "capture", 
    "sdk/desktop",
    "sdk/android/native",
    "common/jni-macro",
    "common"
]
