[profile.release]
overflow-checks = false
strip = "debuginfo"
panic = "abort"
debug = false
lto = true

[workspace]
resolver = "2"
members = [
    "codec", 
    "exports",
    "transport", 
    "jni-macro",
    "sync", 
    "devices", 
    "broadcast"
]
