[profile.release]
debug-assertions = false
overflow-checks = false
strip = "debuginfo"
panic = "abort"
debug = false
lto = true

[workspace]
resolver = "2"
members = [
    "codec",
    "common",
    "capture",
    "transfer",
    "transport", 
    "sdk/desktop",
    "sdk/android/mirror/src/main/native",
    "sdk/android/mirror/src/main/macro",
]
