[profile.release]
overflow-checks = false
strip = "debuginfo"
panic = "abort"
debug = false
lto = true
debug-assertions = false

[workspace]
resolver = "2"
members = [
    "codec", 
    "transport", 
    "devices", 
    "multicast",
    "sdk/desktop",
    "sdk/android/jni-exports",
    "common/jni-macro",
    "common",
]
