[profile.release]
debug-assertions = false
overflow-checks = false
strip = "debuginfo"
panic = "abort"
debug = false
lto = true

[workspace]
resolver = "2"
members = [
    "common",
    "codec",
    "resample",
    "capture",
    "renderer",
    "hylarana",
    "server",
    "transport",
    "examples/rust", 
    "discovery",
    "sdk/android/hylarana/src/main/ffi", 
    "app",
]
