[profile.release]
debug-assertions = false
overflow-checks = false
strip = "debuginfo"
panic = "abort"
debug = false
lto = true

[workspace]
resolver = "2"
members = [
    "utils",
    "codec",
    "service",
    "capture",
    "transport",
    "sdk/desktop",
    "sdk/renderer",
    "sdk/android/mirror/src/main/native",
    "sdk/android/mirror/src/main/macro",
    "multicast",
    "srt", 
    "frame", "new-codec",
]
