[profile.release]
debug-assertions = false
overflow-checks = false
strip = "debuginfo"
panic = "abort"
debug = false
lto = true

[workspace]
resolver = "2"
members = [
    "codec",
    "capture",
    "graphics",
    "mirror",
    "service",
    "transport",
    "common/jni-macro",
    "common/multicast",
    "common/srt",
    "common/frame",
    "common/utils",
    "ffi/mirror",  
]
