[package]
name = "rtp"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
sync = { path = "../sync" }

[dev-dependencies]
tokio = { version = "*", features = ["full"]}
anyhow = "1.0.81"

[build-dependencies]
anyhow = "1.0.81"
cc = "1.0.90"
