[package]
name = "broadcast"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
log = "0.4.21"
thiserror = "1.0.58"
tokio = { version = "1", features = ["net"]}

[dev-dependencies]
tokio = { version = "1", features = ["full"]}
anyhow = "1.0.81"
