[package]
name = "mirror-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.82"
log = "0.4.20"
napi = { version = "3.0.0-alpha.11", features = ["napi9"] }
napi-derive = "3.0.0-alpha.11"
mirror = { version = "0.1", path = "../../mirror" }
simple_logger = "5"
winit = "0.30.5"

[build-dependencies]
napi-build = "1"
