[package]
name = "hylarana-server"
version = "0.3.1"
edition = "2021"
description = "A cross-platform screen casting library implemented by Rust."
license = "LGPL-2.1-only"
readme = "../README.md"
repository = "https://github.com/mycrl/hylarana"

[dependencies]
anyhow = "1.0"
log = "0.4"
simple_logger = "4"
common = { path = "../common", version = "0.3.1", package = "hylarana-common" }
transport = { path = "../transport", version = "0.3.1", package = "hylarana-transport" }
clap = { version = "4", features = ["derive"] }
mimalloc = { version = "0.1", default-features = false }
parking_lot = "0.12"
