[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
log = "0.4.20"
common = { path = "../common" }
srt = { path = "../networks/srt" }
multicast = { path = "../networks/multicast" }
service = { path = "../service" }
smallvec = "1.13.2"

[target.'cfg(target_os = "windows")'.dev-dependencies]
libyuv = "0.1.2"

[dev-dependencies]
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1.0.79"
simple_logger = "4"
