[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
log = "0.4.20"
srt = { path = "../srt" }
multicast = { path = "../multicast" }
common = { path = "../common" }
service = { path = "../service" }
xxhash-rust = { version = "0.8.5", features = ["xxh3"]}
smallvec = "1.13.2"
crossbeam = "0.8.4"
