[package]
name = "frame"
version = "0.1.0"
edition = "2021"

[dependencies]
rubato = "0.15.0"
utils = { path = "../utils" }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58.0"
features = [
    "Win32_System_Com",
    "Win32_Graphics",
    "Win32_Graphics_Direct3D11",
]
