[package]
name = "devices"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
common = { path = "../common" }

[dev-dependencies]
anyhow = "1.0.80"
minifb = "0.25"
libyuv = "0.1.2"

[build-dependencies]
cc = "1.0.88"
anyhow = "1.0.80"
