[package]
name = "jni-exports"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "mirror_android"

[dependencies]
async-trait = "0.1.77"
bytes = "1.5"
transport = { path = "../transport", features = ["android", "frame-drop"] }
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread"] }
log = { version = "0.4.20", features = ["std"]}
num_cpus = "1.16.0"
jni = "0.21.1"
common = { path = "../../../common"}
codec = { path = "../../../codec", features = ["android", "frame-drop"] }
anyhow = "1.0.79"
mimalloc = { version = "*", default-features = false }
jni-macro = { path = "../../../jni-macro" }
