[package]
name = "hylarana-resample"
version = "0.2.0"
edition = "2021"
description = "A cross-platform screen casting library implemented by Rust."
license = "LGPL-2.1-only"
readme = "../README.md"
repository = "https://github.com/mycrl/hylarana"

[dependencies]
rubato = "0.16.1"
common = { path = "../common", version = "0.2.0", package = "hylarana-common" }
