[package]
name = "hylarana-resample"
version = "0.3.0"
edition = "2021"
description = "A cross-platform screen casting library implemented by Rust."
license = "LGPL-2.1-only"
readme = "../README.md"
repository = "https://github.com/mycrl/hylarana"

[dependencies]
common = { path = "../common", version = "0.3.0", package = "hylarana-common" }
thiserror = "2.0"

[dependencies.ffmpeg]
package = "hylarana-ffmpeg-sys"
default-features = false
version = "0.1" 
features = ["swresample"]
