[package]
name = "transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
log = "0.4.20"
os_socketaddr = "0.2.5"
common = { path = "../common" }

[dev-dependencies]
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1.0.79"

[build-dependencies]
anyhow = "1.0.79"
