[package]
name = "multicast"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
socket2 = "0.5.6"
once_cell = "1.19.0"
xxhash-rust = { version = "0.8.5", features = ["xxh3"]}
tokio = { version = "1.37.0", features = ["net", "sync", "macros", "rt-multi-thread"]}
