[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "renderer"

[dependencies]
anyhow = "1.0.86"
cpal = "0.15.3"
utils = { path = "../../utils" }
frame = { path = "../../frame" }
log = "0.4.20"

[target.'cfg(target_os = "windows")'.dependencies]
sdl2 = { version = "0.37.0", features = ["bundled", "static-link","raw-window-handle"] }

[target.'cfg(target_os = "linux")'.dependencies]
sdl2 = { version = "0.37.0", features = ["bundled", "raw-window-handle"] }
