[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "renderer"

[dependencies]
anyhow = "1.0.86"
cpal = "0.15.3"
utils = { path = "../../utils" }
frame = { path = "../../media/frame" }
log = "0.4.20"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58.0"
