[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "renderer"

[dependencies]
anyhow = "1.0.86"
common = { path = "../../common" }
log = "0.4.22"
rodio = "0.19.0"
pollster = "0.3.0"

[dependencies.wgpu]
version = "0.20"
default-features = false
features = [
    "dx12",
    "wgsl",
    "api_log_info",
]
