[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "renderer"

[dependencies]
anyhow = "1.0.86"
common = { path = "../../common" }
sdl2 = { version = "0.37.0", features = ["bundled", "static-link", "raw-window-handle"] }
log = "0.4.20"
cpal = "0.15.3"
rubato = "0.15.0"
