[package]
name = "mirror-codec"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
thiserror = "1.0.63"
mirror-common = { path = "../common", version = "0.1" }
mirror-ffmpeg-sys = { path = "../../mirror-ffmpeg-sys", features = [
    "avcodec",
    "avdevice",
    "avutil",
] }
