[package]
name = "codec"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
utils = { path = "../utils" }
frame = { path = "../frame" }

[build-dependencies]
cc = "1.0.88"
anyhow = "1.0.80"
