[package]
name = "codec"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-sys-next = { path = "../../rust-ffmpeg-sys" }
frame = { path = "../frame" }
utils = { path = "../utils" }
thiserror = "1.0.63"
log = "0.4.20"
