[package]
name = "codec"
version = "0.1.0"
edition = "2021"

[dependencies]
frame = { path = "../frame" }
ffmpeg-sys-next = "7.0.2"
thiserror = "1.0.63"
utils = { path = "../utils" }
log = "0.4.20"

[target.'cfg(target_os = "windows")'.dependencies]
windows-core = "0.58.0"
