[package]
name = "hylarana-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
winit.workspace = true
log.workspace = true
simple_logger.workspace = true
hylarana = { workspace = true, features = ["serde"] }
