[package]
name = "hylarana-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
hylarana = { path = "../../hylarana", features = ["serde", "serde-short"]}
winit = "0.30"
simple_logger = "5"
log = "0.4"
