[package]
name = "jni-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "2"
features = [
    "full", 
    "extra-traits", 
    "derive", 
    "printing", 
    "parsing"
]
