name: publish release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - debug
          - release
        version:
          - ffmpeg6
          - ffmpeg4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: '${{ matrix.target }}-cargo-${{ hashFiles(''**/Cargo.lock'') }}'
      - name: Build distributions (FFmpeg 6.1)
        if: matrix.version == 'ffmpeg6'
        run: npm run build:${{ matrix.target }}
      - name: Build distributions (FFmpeg 4.4)
        if: matrix.version == 'ffmpeg4'
        run: npm run build:ffmpeg4-${{ matrix.target }}
      - name: Compress distributions
        run: Compress-Archive -Path ./build -DestinationPath ./windows-x64-${{ matrix.target }}-${{ matrix.version }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-x64-${{ matrix.target }}-${{ matrix.version }}
          path: ./windows-x64-${{ matrix.target }}-${{ matrix.version }}.zip
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: artifacts/**/*
