name: publish release
on:
    push:
        branches:
            - main
        tags:
            - "*"
jobs:
    build:
        runs-on: "${{ matrix.os }}"
        strategy:
            matrix:
                os:
                    - windows-latest
                    - macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      node_modules/
                      target/
                  key: "${{ matrix.os }}-cargo"

            - name: Set up JDK
              if: runner.os == 'Macos'
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Set up Android SDK and NDK
              if: runner.os == 'Macos'
              uses: android-actions/setup-android@v2
              with:
                  sdk-version: 35
                  ndk-version: 27.0.12077973

            - name: Setup project
              run: |
                  npm i -g yarn
                  yarn

            # installation of dependencies
            - name: Installation of dependencies
              id: dependencies
              if: runner.os == 'Macos'
              run: |
                  brew install ffmpeg@7 cmake wget
                  echo "${{ secrets.ANDROID_RELEASE_KEY }}" | base64 -d > apk-release-key.jks
                  echo "apk_release_key_file=$(pwd)/apk-release-key.jks" >> $GITHUB_OUTPUT
                  echo "sdk.dir=$ANDROID_SDK_ROOT" > ./applications/android/local.properties
                  echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/27.0.12077973" >> ./applications/android/local.properties
                  echo $(ls $ANDROID_SDK_ROOT/ndk)

            # use auto build script
            - name: Build distributions (Windows)
              if: runner.os == 'Windows'
              run: |
                  yarn build:app:release

            - name: Build distributions (Macos)
              if: runner.os == 'Macos'
              run: |
                  yarn build:app:release

            - name: Build APK (Macos)
              if: runner.os == 'Macos'
              env:
                  ANDROID_RELEASE_KEY_FILE: ${{ steps.dependencies.outputs.apk_release_key_file }}
                  ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
              run: |
                  yarn build:android

            # compress shared libraries
            - name: Compress distributions (Windows)
              if: runner.os == 'Windows'
              run: Compress-Archive -Path ./target/app -DestinationPath ./hylarana-windows-x64.zip

            - name: Compress distributions (Macos)
              if: runner.os == 'Macos'
              run: tar -czvf hylarana-darwin-arm64.tar.gz -C ./target/app .

            # upload to artifact
            - name: Upload artifact (Windows)
              if: runner.os == 'Windows'
              uses: actions/upload-artifact@v4
              with:
                  name: hylarana-windows-x64
                  path: ./hylarana-windows-x64-.zip

            - name: Upload artifact (Macos)
              if: runner.os == 'Macos'
              uses: actions/upload-artifact@v4
              with:
                  name: hylarana-darwin-arm64
                  path: ./hylarana-darwin-arm64.tar.gz

            - name: Upload artifact (Android)
              if: runner.os == 'Macos'
              uses: actions/upload-artifact@v4
              with:
                  name: android-apk
                  path: ./target/app/Hylarana.apk

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download All Artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts
            - name: Set release name
              id: set_name
              run: |
                  if [[ "$GITHUB_REF" == refs/heads/main ]]; then
                    release_name=$(date +"%Y-%m-%d_%H-%M-%S")
                  elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
                    release_name=${GITHUB_REF#refs/tags/}
                  else
                    release_name="release"
                  fi
                  echo "release_name=$release_name" >> $GITHUB_OUTPUT
            - name: Create release
              id: create_release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              with:
                  tag_name: ${{ github.ref_name }}
                  name: ${{ steps.set_name.outputs.release_name }}
                  draft: false
                  prerelease: false
                  files: artifacts/**/*
